### ISSUE TITLE
Property values wrongly treated as item ids

### ISSUE THREAD

**Issue by mineo** [google/primarysources#20]
https://www.wikidata.org/wiki/Q315711 and https://www.wikidata.org/wiki/Q1095520 both suggest a MusicBrainz artist id (p434) at the moment and treat the value of the new property as an item id, making them links to https://www.wikidata.org/wiki/885ae336-ef63-465d-a0e7-bdc0a5b788e8 and https://www.wikidata.org/wiki/A10adbf0-448a-455a-99da-75c84df6f1e8 which do not work.

**Comment by tomayac** [comment]
Thanks, this is a (rare) but known problem. I'm adding types one-by-one upon errors occurring and time permitting (currently traveling and backlogged), but was struggling with finding a complete list of types and API representation examples. Does such list exist?

**Comment by mineo** [comment]
I'm not sure I understand "API representation examples" correctly, but is the [formatter url](https://www.wikidata.org/wiki/Property:P1630) property what you mean?

**Comment by Tpt** [comment]
Should be fixed by change c2a546de6b79bfe51d1e9beb2efb42c0adacb65a

**Comment by mineo** [comment]
I don't think this is fixed. https://www.wikidata.org/wiki/Q1095520 now suggests a10adbf0-448a-455a-99da-75c84df6f1e8 as a MusicBrainz artist ID, but it's no longer a hyperlink at all. The same is true for the massive amount of Freebase IDs as well - you have to manually build the URL to actually check if it's the correct identifier, which is very tedious.

**Comment by Tpt** [comment]
Thank you for the report. This issue is now fixed by https://github.com/google/primarysources/commit/07478178434733d2ad554711e2ec86db694a04dd

**Comment by mineo** [comment]
Did you already deploy that? https://www.wikidata.org/wiki/Q1095520 is still showing the value from my earlier comment as plain text.

**Comment by Tpt** [comment]
> Did you already deploy that?

Yes, I haven't deployed it yet. It's deployed now.
